function [png] = generator_pdf()

png.PN_name = 'Scheduler';

%The name of all the places in the Petri net
png.set_of_Ps = {'pJobUnits', 'pReadyQueue', 'pExecute', 'pJobDone',... 
    'pTrigger', 'pReady'};

%The name of all the transitions in the Petri net
png.set_of_Ts = {'tColorizer', 'tProcess', 'tNcs', 'tCs', 'tColorRemover'};

%The relationship between transitions and places in the Petri net
png.set_of_As = {'pJobUnits', 'tColorizer', 1,... 
    'tColorizer', 'pReadyQueue', 1,...
    'pReadyQueue', 'tProcess', 1,...
    'tProcess', 'pExecute', 1,...
    'pExecute', 'tCs', 1,...
    'pExecute', 'tNcs', 1,...
    'tNcs', 'pJobDone', 1,...
    'tCs', 'pJobDone', 1,...
    'tNcs', 'pTrigger', 1,...
    'tCs', 'pTrigger', 1,...
    'pTrigger', 'tColorRemover', 1,...
    'tColorRemover', 'pReady', 1,... 
    'pReady', 'tProcess', 1};